In [1]:
import numpy as np
import matplotlib.pyplot as plt
import random
from scipy.spatial import Voronoi # 冯洛诺伊
from scipy.spatial import ConvexHull
from scipy import stats

In [2]:
def dot2(u, v): # 二维向量点乘
    return u[0]*v[0] + u[1]*v[1]
def calculate_d(A,B):  # 计算二维点 A 和 B 之间的距离
    C = np.array(A) - np.array(B)
    d = C[0]*C[0] + C[1]*C[1]
    return d**0.5

In [3]:
# 平面立方晶格的倒格子仍为平面立方晶格
def init_points(num):
    xx = np.arange(-num, num+1)
    yy = np.arange(-num, num+1)
    X, Y = np.meshgrid(xx, yy)
    return X, Y

def find_nnearest(X, Y):
    len_x = X.shape[0]; len_y = X.shape[1]
    ds = np.ones((len_x, len_y))  
    n_dict = dict()
    for i in range(len_x):
        for j in range(len_y):
            point = [X[i,j], Y[i,j]]
            d = calculate_d([0,0], point)
            ds[i,j] = d
    ds = ds.flatten()
    ranks = stats.rankdata(ds,method='min').reshape((len_x,len_y))
    print(ranks)
    for i in range(len_x):
        for j in range(len_y):
            try:
                n_dict[ranks[i,j]].append([X[i,j], Y[i,j]])
            except:
                n_dict[ranks[i,j]] = [[X[i,j], Y[i,j]]]
    return n_dict

In [4]:
def randomcolor():
    colorArr = ['1','2','3','4','5','6','7','8','9','A','B','C','D','E','F']
    color = ""
    for i in range(6):
        color += colorArr[random.randint(0,14)]
    return "#"+color

In [34]:
def v_plot(nnearest_points, ax1):
    nnearest_points.append([0,0])
    
    vor = Voronoi(np.array(nnearest_points))
    # 画 vonronoi 多面体
    points = vor.points
    vor_vertices = vor.vertices  # vonronoi 多面体的顶点
    point_region = vor.point_region 
    #print(point_region[-1]) # [0,0]所在的 Voronoi 区域
    open_regions = []; vor_regions = []  
    __vor_regions = vor.regions
    for i in range(len(__vor_regions)):
        if -1 not in __vor_regions[i]:
            vor_regions.append(__vor_regions[i])
        else:
            open_regions.append(i)
    current_region = point_region[-1]
    print(__vor_regions[current_region])
    current_points = np.array([vor_vertices[vert_id] for vert_id in __vor_regions[current_region]])
    print(current_points)
    
    lines = []
    if len(current_points) >= 3:
        current_hull = ConvexHull(current_points).simplices.tolist()
        current_hull = np.append(current_hull, current_hull[0])
        color = randomcolor()
        for simplex in current_hull:
            lines = ax1.plot(points[simplex, 0], points[simplex, 1], 'k-', c=color, lw=2)
        print('done')
    else:
        print('Error!')

    return lines

In [35]:
num = 5; n_max = 10
left, width = 0.1, 1; bottom, height = 0.1, 1; spacing = 0.1
rect1 = [left*0, bottom, width, height]
fig = plt.figure(figsize=(16,16))
ax1 = fig.add_axes(rect1)

X, Y = init_points(num)
nnearest_dict = find_nnearest(X, Y)
keys = list(nnearest_dict.keys())
keys.sort()
ax1.scatter(X, Y, c='k', s=4)

n = 1
for key in keys:
    nnearest_points = nnearest_dict[key]
    #print(nnearest_points)
    if n <= n_max:
        if len(nnearest_points)>=2:
            line1 = v_plot(nnearest_points, ax1=ax1) # 绘图函数
            plt.legend(line1, ['第 '+str(n)+' 布里渊区'])
            n = n+1

        
plt.savefig('布里渊区.png',bbox_inches = 'tight')
plt.close()
        

[[118 110 102  90  82  70  82  90 102 110 118]
 [110  98  70  62  50  46  50  62  70  98 110]
 [102  70  58  38  30  26  30  38  58  70 102]
 [ 90  62  38  22  14  10  14  22  38  62  90]
 [ 82  50  30  14   6   2   6  14  30  50  82]
 [ 70  46  26  10   2   1   2  10  26  46  70]
 [ 82  50  30  14   6   2   6  14  30  50  82]
 [ 90  62  38  22  14  10  14  22  38  62  90]
 [102  70  58  38  30  26  30  38  58  70 102]
 [110  98  70  62  50  46  50  62  70  98 110]
 [118 110 102  90  82  70  82  90 102 110 118]]
[3, 1, 0, 2]
[[ 0.5  0.5]
 [ 0.5 -0.5]
 [-0.5 -0.5]
 [-0.5  0.5]]
done
[3, 1, 0, 2]
[[ 0.  1.]
 [-1.  0.]
 [ 0. -1.]
 [ 1.  0.]]
done
[3, 1, 0, 2]
[[ 1.  1.]
 [ 1. -1.]
 [-1. -1.]
 [-1.  1.]]
done
[7, 1, 2, 3, 4, 5, 0, 6]
[[ 0.         -1.25      ]
 [-0.83333333 -0.83333333]
 [-1.25        0.        ]
 [-0.83333333  0.83333333]
 [ 0.          1.25      ]
 [ 0.83333333  0.83333333]
 [ 1.25        0.        ]
 [ 0.83333333 -0.83333333]]
done
[3, 1, 0, 2]
[[ 0.  2.]
 [-2.  0.]
 [ 

In [ ]:
points = np.array([[0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2],
                   [2, 0], [2, 1], [2, 2]])
from scipy.spatial import Voronoi, voronoi_plot_2d
vor = Voronoi(points)

In [21]:
nnearest_dict

{118: [[-5, -5], [5, -5], [-5, 5], [5, 5]],
 110: [[-4, -5], [4, -5], [-5, -4], [5, -4], [-5, 4], [5, 4], [-4, 5], [4, 5]],
 102: [[-3, -5], [3, -5], [-5, -3], [5, -3], [-5, 3], [5, 3], [-3, 5], [3, 5]],
 90: [[-2, -5], [2, -5], [-5, -2], [5, -2], [-5, 2], [5, 2], [-2, 5], [2, 5]],
 82: [[-1, -5], [1, -5], [-5, -1], [5, -1], [-5, 1], [5, 1], [-1, 5], [1, 5]],
 70: [[0, -5],
  [-3, -4],
  [3, -4],
  [-4, -3],
  [4, -3],
  [-5, 0],
  [5, 0],
  [-4, 3],
  [4, 3],
  [-3, 4],
  [3, 4],
  [0, 5]],
 98: [[-4, -4], [4, -4], [-4, 4], [4, 4]],
 62: [[-2, -4], [2, -4], [-4, -2], [4, -2], [-4, 2], [4, 2], [-2, 4], [2, 4]],
 50: [[-1, -4], [1, -4], [-4, -1], [4, -1], [-4, 1], [4, 1], [-1, 4], [1, 4]],
 46: [[0, -4], [-4, 0], [4, 0], [0, 4]],
 58: [[-3, -3], [3, -3], [-3, 3], [3, 3]],
 38: [[-2, -3], [2, -3], [-3, -2], [3, -2], [-3, 2], [3, 2], [-2, 3], [2, 3]],
 30: [[-1, -3], [1, -3], [-3, -1], [3, -1], [-3, 1], [3, 1], [-1, 3], [1, 3]],
 26: [[0, -3], [-3, 0], [3, 0], [0, 3]],
 22: [[-2, -2], [2,

In [ ]:
np.array(list(nnearest_dict.keys()))

In [ ]:
X